kubectl taint node node-01 app=demo:NoSchedule
# Tainting a node to prevent scheduling of pods that do not tolerate the taint

cat <<EOF > toleration.yaml

apiVersion: v1
kind: Pod
metadata:
  name: pod-with-tolerations
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "demo"
    effect: "NoSchedule"
EOF

kubectl apply -f toleration.yaml